[package]
name = "unityledger"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.2"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
